### ISSUE TITLE
Зауваження до записки

### ISSUE THREAD

**Issue by BrunIF** [ploska4/Dyplom_Project_Parada_I#4]
- Код в тексті записки давати: шрифт - 12, Courier New
- у тексті, коли зустрічається _.span2_ або інші змінні, робити їх курсивом

> сітки — наперед задані розміри колонок, які можна відразу ж використовувати, наприклад ширина колонки 90px відноситься до класу .span2, який ми можемо використовувати в CSS описі документа;

p.s. Чекаю продовження ;)

**Comment by ploska4** [comment]
Змінив форматування коду.
Додав 3й і 4й розділи.

**Comment by BrunIF** [comment]
- по тексту необхідно розставити посилання на літературу у відповідності до її використання/ Дуже мало джерел =(
- по кожному розділу потрібно підвести підсумок зробленого (висновок)
- не реалізована і не описана можливість інтегрування в інші ресурси (iframe)
